name: ar-policy-tuning
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - pillow=11.1.0
  - tqdm=4.67.1
  - pip:
      - open_clip_torch==2.32.0
      - hpsv2==1.2.0
      - huggingface_hub>=0.20.0
